apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-example-app-main-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istio-example-app-main
  template:
    metadata:
      labels:
        app: istio-example-app-main
    spec:
      containers:
      - name: istio-example-app-main
        image: shiro16/istio-examples-main:0.0.7
        ports:
        - containerPort: 9080
        args:
        - ./app
