apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-example-app-main-vs
spec:
  hosts:
  - istio-example-app-main-svc
  http:
  - route:
    - destination:
        host: istio-example-app-main-svc
    retries:
      attempts: 1
      perTryTimeout: 2.5s
      retryOn: reset
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-example-app-sub-vs
spec:
  hosts:
  - istio-example-app-sub-svc
  http:
  - route:
    - destination:
        host: istio-example-app-sub-svc
    retries:
      attempts: 3
      perTryTimeout: 3s
      retryOn: reset,gateway-error,connect-failure,refused-stream
